//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernDev.VineClient.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockJsonResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockJsonResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernDev.VineClient.Tests.MockJsonResponses", typeof(MockJsonResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;username&quot;:&quot;virtyaluk&quot;,&quot;avatarUrl&quot;:&quot;http://v.cdn.vine.co/avatars/default.png&quot;,&quot;clientFlags&quot;:{&quot;findPeopleTabs&quot;:[&quot;suggested&quot;,&quot;twitter&quot;,&quot;facebook&quot;,&quot;contacts&quot;],&quot;alwaysShowTimeInFeed&quot;:1,&quot;shouldRenux&quot;:1,&quot;nuxHideFriendsFinder&quot;:0,&quot;useHeartIcons&quot;:1,&quot;followSuggestionsSelectAll&quot;:1,&quot;canShareToFacebookProfileVideo&quot;:1,&quot;followSuggestions&quot;:1,&quot;showDiscoverFeedCard&quot;:0,&quot;audioNumChannels&quot;:2,&quot;audioRemix&quot;:1,&quot;profile_sorting&quot;:1,&quot;similarPosts&quot;:1,&quot;scribeEnabled&quot;:1,&quot;disableContactsTwitterPrompt&quot;:1,&quot;useDigitsForPho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string authResponse {
            get {
                return ResourceManager.GetString("authResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;count&quot;:17,&quot;records&quot;:[{&quot;featuredChannelId&quot;:1337983201704087552,&quot;channelId&quot;:1337934322912907264,&quot;showRecent&quot;:1,&quot;iconUrl&quot;:&quot;/static/api/collections_icon.png&quot;,&quot;fontColor&quot;:&quot;ffffff&quot;,&quot;event&quot;:0,&quot;exploreName&quot;:&quot;bath bombs&quot;,&quot;exploreIconFullUrl&quot;:&quot;&quot;,&quot;backgroundImageUrl&quot;:&quot;https://vines.s3.amazonaws.com/static/api/watermleon.gif&quot;,&quot;vanityUrl&quot;:&quot;bath-bombs&quot;,&quot;priority&quot;:301,&quot;exploreRetinaIconFullUrl&quot;:&quot;http://v.cdn.vine.co/static/api/collections_retinaexplore.png&quot;,&quot;backgroundColor&quot;:&quot;FF7AAE&quot;,&quot;channel&quot;:&quot;bath bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string channelRecordsList {
            get {
                return ResourceManager.GetString("channelRecordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;username&quot;:&quot;Graham Alston&quot;,&quot;comment&quot;:&quot;song?&quot;,&quot;verified&quot;:0,&quot;vanityUrls&quot;:[],&quot;created&quot;:&quot;2016-05-02T03:19:02.000000&quot;,&quot;userId&quot;:985402855928315904,&quot;profileBackground&quot;:&quot;0x7870cc&quot;,&quot;entities&quot;:[],&quot;user&quot;:{&quot;username&quot;:&quot;Graham Alston&quot;,&quot;verified&quot;:0,&quot;description&quot;:&quot;&quot;,&quot;twitterVerified&quot;:0,&quot;avatarUrl&quot;:&quot;http://v.cdn.vine.co/avatars/default.png&quot;,&quot;notPorn&quot;:0,&quot;userId&quot;:985402855928315904,&quot;profileBackground&quot;:&quot;0x7870cc&quot;,&quot;hideFromPopular&quot;:0,&quot;private&quot;:0,&quot;location&quot;:&quot;&quot;,&quot;unflaggable&quot;:0,&quot;vanityUrls&quot;:[]},&quot;commentId&quot;:13387 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commentResponse {
            get {
                return ResourceManager.GetString("commentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;: &quot;&quot;, &quot;data&quot;: {}, &quot;success&quot;: true, &quot;error&quot;: &quot;&quot;}.
        /// </summary>
        internal static string emptyResponse {
            get {
                return ResourceManager.GetString("emptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;username&quot;:&quot;JustMiso&quot;,&quot;verified&quot;:0,&quot;vanityUrls&quot;:[],&quot;created&quot;:&quot;2016-05-02T04:09:07.000000&quot;,&quot;userId&quot;:1338770960601493504,&quot;user&quot;:{&quot;private&quot;:0},&quot;likeId&quot;:1338771225023283200},&quot;success&quot;:true,&quot;error&quot;:&quot;&quot;}.
        /// </summary>
        internal static string likeResponse {
            get {
                return ResourceManager.GetString("likeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;: &quot;&quot;, &quot;data&quot;: 2, &quot;success&quot;: true, &quot;error&quot;: &quot;&quot;}.
        /// </summary>
        internal static string notificationsCount {
            get {
                return ResourceManager.GetString("notificationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;count&quot;:0,&quot;anchorStr&quot;:&quot;&quot;,&quot;records&quot;:[{&quot;body&quot;:&quot;Scuuuuh is now following you&quot;,&quot;displayUserId&quot;:1269274583891419136,&quot;verified&quot;:0,&quot;followRequested&quot;:false,&quot;created&quot;:&quot;2016-05-03T05:43:23.000000&quot;,&quot;following&quot;:false,&quot;userId&quot;:1269274583891419136,&quot;avatarUrl&quot;:&quot;http://v.cdn.vine.co/r/avatars/6357F7BC691303290238076354560_4b4c99317ab.5.1.jpg?versionId=6TmVDDrMBl82LvgbMvIdsV2DNXpPB9cx&quot;,&quot;notificationTypeId&quot;:1,&quot;private&quot;:0,&quot;entities&quot;:[{&quot;type&quot;:&quot;user&quot;,&quot;range&quot;:[0,7],&quot;link&quot;:&quot;vine://user-id/1269274583891419136&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string notificationsRecordsList {
            get {
                return ResourceManager.GetString("notificationsRecordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;count&quot;:1,&quot;anchorStr&quot;:&quot;&quot;,&quot;records&quot;:[{&quot;promoted&quot;:1,&quot;liked&quot;:0,&quot;videoDashUrl&quot;:&quot;http://v.cdn.vine.co/r/videos_dashhd/04E9C9E3891297595087265677312_4f8b7ff5700.5.1.6484865023185249813.mp4?versionId=FA_fgBHu32k1Fg_A_ROhuI6NBAXagdL0&quot;,&quot;foursquareVenueId&quot;:&quot;&quot;,&quot;userId&quot;:980422881370669056,&quot;private&quot;:0,&quot;videoWebmUrl&quot;:null,&quot;loops&quot;:{&quot;count&quot;:57120468.0,&quot;velocity&quot;:3.9173333333333336,&quot;onFire&quot;:0},&quot;thumbnailUrl&quot;:&quot;http://v.cdn.vine.co/r/videos/04E9C9E3891297595087265677312_4f8b7ff5700.5.1.6484865023185249813.m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string postsRecordsList {
            get {
                return ResourceManager.GetString("postsRecordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;created&quot;:&quot;2016-05-02T03:19:02.000000&quot;,&quot;repostId&quot;:1297595204597354496,&quot;postId&quot;:1297595204597354496},&quot;success&quot;:true,&quot;error&quot;:&quot;&quot;}.
        /// </summary>
        internal static string repostResponse {
            get {
                return ResourceManager.GetString("repostResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;: 900, &quot;data&quot;: &quot;&quot;, &quot;success&quot;: false, &quot;error&quot;: &quot;That record does not exist.&quot;}.
        /// </summary>
        internal static string responseError {
            get {
                return ResourceManager.GetString("responseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;count&quot;:0,&quot;anchorStr&quot;:&quot;&quot;,&quot;records&quot;:[{&quot;deleted&quot;:null,&quot;tagId&quot;:1301468743066816512,&quot;tag&quot;:&quot;runningmanchallenge&quot;,&quot;created&quot;:&quot;2016-01-20T05:42:22.000000&quot;},{&quot;deleted&quot;:null,&quot;tagId&quot;:953960899004395520,&quot;tag&quot;:&quot;WWEPayback&quot;,&quot;created&quot;:&quot;2013-06-05T07:10:16.000000&quot;},{&quot;deleted&quot;:null,&quot;tagId&quot;:906545578899681280,&quot;tag&quot;:&quot;BTS&quot;,&quot;created&quot;:&quot;2013-01-25T10:58:43.000000&quot;}],&quot;previousPage&quot;:null,&quot;backAnchor&quot;:&quot;&quot;,&quot;anchor&quot;:null,&quot;nextPage&quot;:null,&quot;size&quot;:20},&quot;success&quot;:true,&quot;error&quot;:&quot;&quot;}.
        /// </summary>
        internal static string tagsRecordsList {
            get {
                return ResourceManager.GetString("tagsRecordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;username&quot;:&quot;Graham Alston&quot;,&quot;comment&quot;:&quot;song?&quot;,&quot;verified&quot;:0,&quot;vanityUrls&quot;:[],&quot;created&quot;:&quot;2016-05-02T03:19:02.000000&quot;,&quot;userId&quot;:985402855928315904,&quot;profileBackground&quot;:&quot;0x7870cc&quot;,&quot;entities&quot;:[],&quot;user&quot;:{&quot;username&quot;:&quot;Graham Alston&quot;,&quot;verified&quot;:0,&quot;description&quot;:&quot;&quot;,&quot;twitterVerified&quot;:0,&quot;avatarUrl&quot;:&quot;http://v.cdn.vine.co/avatars/default.png&quot;,&quot;notPorn&quot;:0,&quot;userId&quot;:985402855928315904,&quot;profileBackground&quot;:&quot;0x7870cc&quot;,&quot;hideFromPopular&quot;:0,&quot;private&quot;:0,&quot;location&quot;:&quot;&quot;,&quot;unflaggable&quot;:0,&quot;vanityUrls&quot;:[]},&quot;commentId&quot;:13387 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string userResponse {
            get {
                return ResourceManager.GetString("userResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:&quot;&quot;,&quot;data&quot;:{&quot;count&quot;:44045,&quot;records&quot;:[{&quot;username&quot;:&quot;Alison Brie&quot;,&quot;twitterScreenname&quot;:&quot;alisonbrie&quot;,&quot;followerCount&quot;:109779,&quot;verified&quot;:1,&quot;vanityUrls&quot;:[],&quot;loopCount&quot;:1910877,&quot;avatarUrl&quot;:&quot;http://v.cdn.vine.co/v/avatars/B9CAC78F-E17B-4CE2-8326-2FDE69D35DFF-11245-000005A6A23F9D2F.jpg?versionId=UqqDiWT7daIJBzfVrbBGLbkv7_Xm0cmD&quot;,&quot;twitterVerified&quot;:1,&quot;userId&quot;:951265490817449984,&quot;profileBackground&quot;:&quot;0xffaf40&quot;,&quot;user&quot;:{&quot;private&quot;:0},&quot;location&quot;:&quot;Los Angeles&quot;},{&quot;username&quot;:&quot;Alison Sweeney&quot;,&quot;twitterScreenname&quot;:&quot;Ali_Sween [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usersRecordsList {
            get {
                return ResourceManager.GetString("usersRecordsList", resourceCulture);
            }
        }
    }
}
